### ISSUE TITLE
No module named 'robot_interface'

### ISSUE THREAD

**Issue by YunxiTang** [yxyang/fast_and_efficient#1]
Hello,
After completing the three setup steps, and also I copied robot_interface.XXX.so file to the main directory. Then, tried to run script convex_mpc_controller_example.py, an error "No module named 'robot_interface" appears. Is there way to fix this issue
Thanks!

**Comment by yxyang** [comment]
Can you try running the script from the main directory using:
```python -m src.convex_mpc_controller.convex_mpc_controller_example```
?

**Comment by YunxiTang** [comment]
Oops, thanks for your reply. It works! Many thanks!
