### ISSUE TITLE
Go1 Support

### ISSUE THREAD

**Issue by simonchamorro** [yxyang/fast_and_efficient#3]
Hi, Thanks for releasing this codebase! 

This runs great on the A1 but we're having some issues getting this work on our Go1.
Have you by any chance also tried running this on the Go1 or do you have any idea what we'd have to adjust to make it work?

Thanks in advance,
Simon

**Comment by yxyang** [comment]
Unfortunately our lab doesn't have a Go1 yet so I cannot test our codebase on Go1. If we get a Go1 in the future, I'll probably update the codebase / create a new repo with Go1 support.

**Comment by yxyang** [comment]
Just FYI, I have created a new branch that supports Go1. The MPC is not very stable yet, and likely some parameters need to be further tuned. But it is at least working. 
https://github.com/yxyang/fast_and_efficient/tree/go1_support

**Comment by simonchamorro** [comment]
Thank you!

**Comment by SangliTeng** [comment]
Hi! Thanks for sharing the GO1 branch!

However, I find that the go1_sdk folder is empty, is this folder missing or I should use some of the existing files?
