### ISSUE TITLE
Motor Position Control with no torques

### ISSUE THREAD

**Issue by Charlescai123** [yxyang/fast_and_efficient#5]
Hi, thank you for the great work and I really appreciate it! I was trying to replicate some results in the paper but encountered some troubles on the real robot.

After the robot stands up, I press L2 + B to transition it into the damping mode. It soon loses forces and subsequently lays down. Reviewing the code in whole_body_controller_example.py, I find there's a reset process for A1Robot initialization, which tries to position the robot under the standing pose. Notably, this process utilizes Motor Position Control Mode for implementation. However, it seems the pure position control mode alone cannot bring the robot to its desired poses without added torques. A related discussion on a similar problem can be found in the Unitree official repository at: https://github.com/unitreerobotics/unitree_legged_sdk/issues/111.

Thus I'm curious whether the code enables the robot to stand up under the pure position control mode?

**Comment by yxyang** [comment]
Hi,

Regardless of the motor control mode I defined in the python code, the code uses the same "hybrid" low-level [control mode](https://github.com/yxyang/fast_and_efficient/blob/master/third_party/unitree_legged_sdk/python_interface.cpp#L46) to interface with the Unitree SDKs. That is, it always sends in a 5-dim vector for each moro, including Kp, Kd, p_ds, v_des and extra torque. Then the [a1_robot.py](https://github.com/yxyang/fast_and_efficient/blob/master/src/robots/a1_robot.py#L11) builds an extra layer on top that enables position or torque control.

Regarding the non-zero position error from position control, my understanding is that this is a classic issue with PD control, which introduces a [steady state error](https://softwareengineering.stackexchange.com/questions/214912/why-does-a-proportional-controller-have-a-steady-state-error) unless an integral term is included. I'm not very familiar with the exact case you are describing though.

Best,
Yuxiang

**Comment by Charlescai123** [comment]
Hi Yuxiang,

I've made a test and think my problem is because the Kp and Kd gain are not set properly which prevents the robot from standing up due to the gravity. Anyhow thank you for the reply! Close it now.

Best,
Yihao
